### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [tiffanydarnick/Splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by tiffanydarnick** [comment]
Hi Ken, I think I may have figured this out. I added the meta tag to the <head> .

**Comment by kenmazaika** [comment]
Thumbs up, Tiffany! :) :+1:
